In [1]:
from  matplotlib import pyplot
import numpy as np

In [2]:
## 변수 지정
# K : 반복 횟수
# ret : 보상계수
# pi : 정책 확률
# Gamma : 감쇠계수
# Per : 전이확률
K=5
ret = -1
Gamma = 1
Per= 1

In [3]:
## 초기행렬 생성
MDP = np.zeros(shape=(4,4))

In [4]:
## 함수 생성

# 행렬간의 연결
def T_cal(Matrix):
    Matrix1=np.zeros(shape=(4,4))
    for j in range(Matrix.shape[1]):
        for i in range(Matrix.shape[0]):
            if i!=3 or j!=3 :
                A_list=[]
                for p in L_cal(Matrix,i,j):
                    A_list.append(O_cal(p))
                    Matrix1[i,j]=max(A_list)
    return Matrix1
                
# 생산 가치 함수                 
def O_cal(M):
    return ret + Gamma * Per * M

# 행렬 내 데이터값의 위치에 따른 계산 함수               
def L_cal(M,i,j):
    A_list=[-1,1]
    B_list=[]
    for k in A_list:
        if 0<=i+k<=M.shape[0]-1:
            B_list.append(M[i+k,j])
        if 0<=j+k<=M.shape[1]-1:
            B_list.append(M[i,j+k])
    return B_list

In [5]:
Result=[]
for i in range(1,6):
    MDP=T_cal(MDP)
    print(MDP)
    Result.append(T_cal(MDP))

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -1.]
 [-2. -2. -1.  0.]]
[[-3. -3. -3. -3.]
 [-3. -3. -3. -2.]
 [-3. -3. -2. -1.]
 [-3. -2. -1.  0.]]
[[-4. -4. -4. -3.]
 [-4. -4. -3. -2.]
 [-4. -3. -2. -1.]
 [-3. -2. -1.  0.]]
[[-5. -5. -4. -3.]
 [-5. -4. -3. -2.]
 [-4. -3. -2. -1.]
 [-3. -2. -1.  0.]]
